project_id = "singular-acumen-401703" 
location = "us-central1"
key_path= "C:\\Users\\vaishnavi\\huggingface-repo\\GraphGeneration-MedicalResearch\\Pages\\singular-acumen-402703-28ef56fd6bdf.json"
url="bolt://localhost:7687"
username="karthiksab" 
password="kartik@1"
index = 'genaibook'